const locaisInstalacao = [
  { id: "lab_informatica", nome: "Laboratório de Informática" },
  { id: "lab_quimica", nome: "Laboratório de Química" },
  { id: "lab_manutencao", nome: "Laboratório de Manutenção" },
  { id: "lab_metrologia", nome: "Laboratório de Metrologia" },
  { id: "ofic_cnc", nome: "Oficina CNC" },
  { id: "ofic_com_eletrica", nome: "Oficina Com Eletrônica" },
  { id: "ofic_eletrica", nome: "Oficina Elétrica" },
  { id: "ofic_geral", nome: "Oficina Geral" },
  { id: "ofic_deposito", nome: "Depósito de Oficina" },
  { id: "ofic_manutencao", nome: "Oficina de Manutenção" },
  { id: "ofic_plastico", nome: "Oficina de Plástico" },
  { id: "ofic_soldagem", nome: "Oficina de Soldagem" },
  { id: "ofic_usinagem", nome: "Oficina de Usinagem" },
  { id: "sala_aula", nome: "Sala de Aula" },
  { id: "sala_302", nome: "Sala de Aula 302" },
  { id: "sala_tecnologia", nome: "Sala de Tecnologia" },
  { id: "sala_auditorio", nome: "Auditório" },
  { id: "mdi", nome: "MDI" },
  { id: "sala_instrutores", nome: "Sala dos Instrutores" },
  { id: "sala_preparacao", nome: "Sala de Preparação" },
  { id: "lab_cozinha", nome: "Laboratório de Cozinha" },
  { id: "sala_patio", nome: "Pátio" },
  { id: "sala_refeitorio", nome: "Refeitório" },
  { id: "sala_agua_reuso", nome: "Água de Reuso" },
  { id: "sala_almoxarifado", nome: "Almoxarifado" },
  { id: "sala_deposito_compra", nome: "Depósito de Compra" },
  { id: "sala_deposito_limpeza", nome: "Depósito de Limpeza" },
  { id: "sala_poliesportivo", nome: "Ginásio Poliesportivo" },
  { id: "sala_banheiro_limpeza", nome: "Banheiros e Limpeza" },
  { id: "sala_zeladoria", nome: "Sala da Zeladoria" },
  { id: "sala_cabine_primaria", nome: "Cabine Primária" },
  { id: "sala_torre_reservatorio", nome: "Torre de Reservatório" },
  { id: "adm_classificacao", nome: "Administração - Classificação" },
  { id: "adm_cris_relacionado", nome: "Administração - CRIS Relacionado" },
  { id: "adm_diretoria", nome: "Administração - Diretoria" },
  { id: "adm_orienteduc", nome: "Administração - Orientação Educacional" },
  { id: "adm_recepcao", nome: "Administração - Recepção" },
  { id: "adm_secretaria", nome: "Administração - Secretaria" },
  { id: "adm_serv_servidor", nome: "Administração - Servidor" },
  { id: "adm_sala_reuniao", nome: "Administração - Sala de Reunião" },
  { id: "adm_portaria", nome: "Administração - Portaria" },
  { id: "bibl_biblioteca", nome: "Biblioteca" },
  { id: "auditorio", nome: "Auditório" },
  { id: "bloco_oficinas", nome: "Bloco de Oficinas" },
  { id: "lab_labeltrodig", nome: "Laboratório de Eletrônica Digital" },
  { id: "lab_hidraulica", nome: "Laboratório de Hidráulica" },
  { id: "lab_informatica", nome: "Laboratório de Informática" },
  { id: "lab_quimica", nome: "Laboratório de Química" },
  { id: "lab_manutencao", nome: "Laboratório de Manutenção" },
  { id: "lab_metrologia", nome: "Laboratório de Metrologia" },
  { id: "ofic_cnc", nome: "Oficina CNC" },
  { id: "ofic_com_eletrica", nome: "Oficina Com Eletrônica" },
  { id: "ofic_eletrica", nome: "Oficina Elétrica" },
  { id: "ofic_geral", nome: "Oficina Geral" },
  { id: "ofic_deposito", nome: "Depósito de Oficina" },
  { id: "ofic_manutencao", nome: "Oficina de Manutenção" },
  { id: "ofic_plastico", nome: "Oficina de Plástico" },
  { id: "ofic_soldagem", nome: "Oficina de Soldagem" },
  { id: "ofic_usinagem", nome: "Oficina de Usinagem" },
  { id: "sala_aula", nome: "Sala de Aula" },
  { id: "sala_302", nome: "Sala de Aula 302" },
  { id: "sala_tecnologia_i", nome: "Sala de Tecnologia I" },
  { id: "sala_tecnologia_ii", nome: "Sala de Tecnologia II" },
  { id: "sala_tecnologia_iii", nome: "Sala de Tecnologia III" },
  { id: "sala_aapm", nome: "Sala AAPM" },
  {
    id: "sala_anq_anqualavida",
    nome: "Sala ANQ - Análise da Qualidade de Vida",
  },
];

const locaisArray = Array.from(
  new Map(locaisInstalacao.map((item) => [item.id, item])).values()
);

//Ordem alfabetica
const locaisUnicos = locaisArray.sort((a, b) =>
  a.nome.localeCompare(b.nome)
);

module.exports = locaisUnicos;
