const locaisInstalacao = [
  { id: "adm_classificacao", nome: "Administração - Classificação" },
  { id: "adm_cris_relacionado", nome: "Administração - CRIS Relacionado" },
  { id: "adm_diretoria", nome: "Administração - Diretoria" },
  { id: "adm_orienteduc", nome: "Administração - Orientação Educacional" },
  { id: "adm_portaria", nome: "Administração - Portaria" },
  { id: "adm_recepcao", nome: "Administração - Recepção" },
  { id: "adm_secretaria", nome: "Administração - Secretaria" },
  { id: "adm_serv_servidor", nome: "Administração - Servidor" },
  { id: "adm_sala_reuniao", nome: "Administração - Sala de Reunião" },
  { id: "auditório", nome: "Auditório" },
  { id: "bibl_biblioteca", nome: "Biblioteca" },
  { id: "bloco_oficinas", nome: "Bloco de Oficinas" },
  { id: "compressor", nome: "Compressor" },
  { id: "copa", nome: "Copa" },
  { id: "deposito_compra", nome: "Depósito de Compra" },
  { id: "deposito_limpeza", nome: "Depósito de Limpeza" },
  { id: "deposito_oficina_eletrica", nome: "Depósito Oficina Elétrica" },
  { id: "deposito_oficina_mecanica", nome: "Depósito Oficina Mecânica" },
  { id: "empilhadeira", nome: "Empilhadeira" },
  { id: "empilhadeira_eletrica", nome: "Empilhadeira Elétrica" },
  { id: "gas_empilhadeira", nome: "Gás Empilhadeira" },
  { id: "ginásio_poliesportivo", nome: "Ginásio Poliesportivo" },
  { id: "lab_automacao", nome: "Laboratório Automação" },
  { id: "lab_cad", nome: "Laboratório de CAD" },
  { id: "lab_clp", nome: "Laboratório CLP" },
  { id: "lab_eletronica_analogica", nome: "Laboratório Eletrônica Analógica" },
  { id: "lab_eletronica_digital", nome: "Laboratório Eletrônica Digital" },
  { id: "lab_hidraulica", nome: "Laboratório de Hidráulica" },
  { id: "lab_informatica_01", nome: "Laboratório de Informática 01" },
  { id: "lab_informatica_02", nome: "Laboratório de Informática 02" },
  { id: "lab_informatica_03", nome: "Laboratório de Informática 03" },
  { id: "lab_informatica_04", nome: "Laboratório de Informática 04" },
  { id: "lab_informatica_05", nome: "Laboratório de Informática 05" },
  { id: "lab_manutencao", nome: "Laboratório de Manutenção" },
  { id: "lab_metrologia", nome: "Laboratório de Metrologia" },
  { id: "lab_pneumatica", nome: "Laboratório Pneumática" },
  { id: "lab_quimica", nome: "Laboratório de Química" },
  { id: "mdi", nome: "MDI" },
  { id: "oficina_ajustagem", nome: "Oficina Ajustagem" },
  { id: "oficina_cnc", nome: "Oficina CNC" },
  { id: "oficina_com_eletrica", nome: "Oficina Com Eletrônica" },
  { id: "oficina_comandos", nome: "Oficina Comandos" },
  { id: "oficina_deposito", nome: "Depósito de Oficina" },
  { id: "oficina_eletrica", nome: "Oficina Elétrica" },
  { id: "oficina_geral", nome: "Oficina Geral" },
  { id: "oficina_manutencao", nome: "Oficina de Manutenção" },
  { id: "oficina_plastico", nome: "Oficina de Plástico" },
  { id: "oficina_solda", nome: "Oficina de Solda" },
  { id: "oficina_usinagem", nome: "Oficina de Usinagem" },
  { id: "patio", nome: "Pátio" },
  { id: "quadra", nome: "Quadra" },
  { id: "sala_aapm", nome: "Sala AAPM" },
  { id: "sala_agua_reuso", nome: "Água de Reuso" },
  { id: "sala_almoxarifado", nome: "Almoxarifado" },
  {
    id: "sala_anq_anqualavida",
    nome: "Sala ANQ - Análise da Qualidade de Vida",
  },
  { id: "sala_banheiro_limpeza", nome: "Banheiros e Limpeza" },
  { id: "sala_cabine_primaria", nome: "Cabine Primária" },
  { id: "sala_desenho", nome: "Sala de Desenho" },
  { id: "sala_docentes", nome: "Sala dos Docentes" },
  { id: "sala_instrutores", nome: "Sala dos Instrutores" },
  { id: "sala_preparacao", nome: "Sala de Preparação" },
  { id: "sala_refeitorio", nome: "Refeitório" },
  { id: "sala_tecnologia_01", nome: "Sala Tecnologia 01" },
  { id: "sala_tecnologia_02", nome: "Sala Tecnologia 02" },
  { id: "sala_tecnologia_03", nome: "Sala Tecnologia 03" },
  { id: "sala_torre_reservatorio", nome: "Torre de Reservatório" },
  { id: "sala_zeladoria", nome: "Sala da Zeladoria" },
];

const locaisArray = Array.from(
  new Map(locaisInstalacao.map((item) => [item.id, item])).values()
);

const locaisUnicos = locaisArray.sort((a, b) => a.nome.localeCompare(b.nome));

module.exports = locaisUnicos;
